### PR TITLE
Fix `NaN` detection in `.is()`

### LINKED ISSUE #160: [v5] Better handling of `NaN`
https://github.com/sindresorhus/ow/issues/231#issuecomment-1047100612

### PR DESCRIPTION
**Pull request by panva**
`NaN` is not a number, this fixes the is() return for it.

before
```js
is(NaN) // => 'number'
```

after
```js
is(NaN) // => 'NaN'
```

---

Fixes #160

### CODE REVIEW

**Comment by panva** [comment]
I think this doesn't have to be considered a breaking but will leave that up to you @sindresorhus.

File: source/index.ts [hunk 1]
```diff
@@ -110,7 +111,7 @@ function is(value: unknown): TypeName {
 		case 'string':
 			return 'string';
 		case 'number':
-			return 'number';
+			return Number.isNaN(value) ? 'NaN' : 'number';
```
Comment (sindresorhus) [inline source/index.ts:114]: I think it would be clearer to do the `NaN` check on line 107.

Comment (panva) [reply source/index.ts:114]: That would mean isNan is ran for everything but `null`, this way it is only ran for what we know `NaN` reports as typeof

Comment (panva) [reply source/index.ts:114]: This optimization can likewise be done for object/null

Comment (sindresorhus) [reply source/index.ts:114]: You are assuming `Number.isNaN` is not optimized. I feel like this is entering premature optimization territory. In practice, the performance difference is probably none or negligible.

**Comment by sindresorhus** [comment]
The PR looks good, but since I'm planning a major release here in a month or two, I'm gonna keep this PR open until such time, as I don't see the point in risking it breaking for someone.

**Comment by sindresorhus** [comment]
Tests are failing.

**Comment by panva** [comment]
[`Number.isNaN`](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-number.isnan) is not defined to only take an argument of type `number`.

I can either `// @ts-ignore` this or put it back to the `number` case. Or you can go investigate why the types for Number.isNaN are messed up in CI ;)

**Comment by sindresorhus** [comment]
Finally out: https://github.com/sindresorhus/is/releases/tag/v5.0.0
